name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Test connection
        run: |
          nc -zv ${{ secrets.HOST }} 22
          
      - name: Deploy with sshpass
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get install -y sshpass
          sshpass -p "$SSH_PASSWORD" ssh -vvv -o StrictHostKeyChecking=no -o ConnectTimeout=60 root@${{ secrets.HOST }} "
            cd /workspace/KINDHABITFE
            git reset --hard
            git pull origin main
            npm install --force
            npm run build
            sudo systemctl restart nginx
          "
