name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.HOST }}
          if_key_exists: replace
          
      - name: Deploy with rsync
        run: |
          ssh -o StrictHostKeyChecking=no -vvv root@${{ secrets.HOST }} "
            cd /workspace/KINDHABITFE
            git reset --hard
            git pull origin main
            npm install --force
            npm run build
            sudo systemctl restart nginx
          "
