name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --force
        
      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        
      - name: Test connection
        run: |
          nc -zv ${{ secrets.HOST }} 22
          
      - name: Deploy with sshpass
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sudo apt-get install -y sshpass
          # Vite의 기본 빌드 디렉토리인 dist 사용
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r dist/* root@${{ secrets.HOST }}:/workspace/KINDHABITFE/build/
          
          # 서버에서 필요한 작업만 수행
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@${{ secrets.HOST }} "
            cd /workspace/KINDHABITFE
            git reset --hard
            git pull origin main
            sudo systemctl restart nginx
          "
